import React from 'react'

export default function CookieUse() {


  
  return (
        <div className='content'>
                    
        
            <h4>Definitions and key terms</h4>
        
            <p>To help explain things as clearly as possible in this Cookie Policy, every time any of these terms are referenced, are strictly defined as:</p>
        
            <p>- Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</p>
            <p>- Company: when this policy mentions &quot;Company&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;, it refers to TuringX, that is responsible for your information under this Cookie Policy.</p>
            <p>- Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit TuringX Websites or Applications and use the services.</p>
            <p>- Personal Data: any information that directly, indirectly, or in connection with other information - including a personal identification number - allows for the identification or identifiability of a natural person.</p>
            <p>- Service: refers to the service provided by TuringX and on this platform.</p>
            <p>- Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</p>
            <p>- Website: TuringX Assist&apos;s site, which can be accessed via this URL: www.assist.turingx.in</p>
            <p>- You: a person or entity that is registered with TuringX to use the Services.</p>
        
            <h4>Introduction</h4>
        
            <p>This Cookie Policy explains how TuringX and its affiliates (collectively &quot;TuringX&quot;, &quot;Company&quot;, &quot;we&quot;, &quot;us&quot;, and &quot;ours&quot;), use cookies and similar technologies to recognize you when you visit our website, including without limitation www.turingx.in and any related URLs, mobile or localized versions and related domains/sub-domains (&quot;Websites&quot;). It explains what these technologies are and why we use them, as well as the choices for how to control them.</p>
        
            <h4>What is a cookie?</h4>
        
            <p>A cookie is a small text file that is stored on your computer or other internet connected device in order to identify your browser, provide analytics, remember information about you such as your language preference or login information. They&apos;re completely safe and can&apos;t be used to run programs or deliver viruses to your device.</p>
        
            <h4>Why do we use cookies?</h4>
        
            <p>We use first-party and/or third-party cookies on our website for various purposes such as:</p>
        
            <p>- To facilitate the operation and functionality of our website;</p>
            <p>- To improve your experience of our website and make navigating around them quicker and easier;</p>
            <p>- To allow us to make a bespoke user experience for you and for us to understand what is useful or of interest to you;</p>
            <p>- To analyze how our website is used and how best we can customize it;</p>
            <p>- To identify future prospects and personalize marketing and sales interactions with it;</p>
            <p>- To facilitate the tailoring of online advertising to your interests.</p>
        
        
            <h4>What type of cookies does TuringX use?</h4>
        
            <p>Cookies can either be session cookies or persistent cookies. A session cookie expires automatically when you close your browser. A persistent cookie will remain until it expires or you delete your cookies. Expiration dates are set in the cookies themselves; some may expire after a few minutes while others may expire after multiple years. Cookies placed by the website you‚Äôre visiting are called &quot;first party cookies&quot;.</p>
        
            <p>Strictly Necessary cookies are necessary for our website to function and cannot be switched off in our systems. They are essential in order to enable you to navigate around the website and use its features. If you remove or disable these cookies, we cannot guarantee that you will be able to use our website.</p>
        
            <p>We use the following types of cookies in our website:</p>
        
            <p><b>Essential Cookies</b></p>
        
            <p>We use essential cookies to make our website work. These cookies are strictly necessary to enable core functionality such as security, network management, your cookie preferences and accessibility. Without them you wouldn&apos;t be able to use basic services. You may disable these by changing your browser settings, but this may affect how the Websites function.</p>
        
            <p><b>Performance and Functionality Cookies</b></p>
        
            <p>These cookies are used to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously.</p>
        
            <p><b>Marketing Cookies</b></p>
        
            <p>These account-based marketing cookies enable us to identify future prospects and personalize sales and marketing interactions with them.</p>
        
            <p><b>Analytics and Customization Cookies</b></p>
        
            <p>These cookies collect information that is used to help us understand how our website is being used or how effective our marketing campaigns are, or to help us customize our website for you.</p>
            <p>We use cookies served by Google Analytics to collect limited data directly from end-user browsers to enable us to better understand your use of our website. Further information on how Google collects and uses this data can be found at: https://www.google.com/policies/privacy/partners/. You can opt-out of all Google supported analytics on our Websites by visiting: https://tools.google.com/dlpage/gaoptout.</p>
        
            <p><b>Third Party Cookies</b></p>
        
            <p>Some cookies that have been set on our website are not set on a first-party basis by TuringX. The Websites can be embedded with content from third parties to serve advertising. These third-party service providers may set their own cookies on your web browser. Third-party service providers control many of the performance and functionality, advertising, marketing and analytics cookies described above. We do not control the use of these third-party cookies as cookies can only be accessed by the third party that originally set them.</p>
        
            <h4>How you can manage cookies?</h4>
        
            <p>Most browsers allow you to control cookies through their &apos;settings&apos; preferences. However, if you limit the ability of websites to set cookies, you may worsen your overall user experience, since it will no longer be personalized to you. It may also stop you from saving customized settings like login information. Browser manufacturers provide help pages relating to cookie management in their products.</p>
        
            <p>Browser manufacturers provide help pages relating to cookie management in their products. Please see below for more information.</p>
        
            <br />

            <ul>
                <li>- Google Chrome</li>
                <li>- Internet Explorer</li>
                <li>- Mozilla Firefox</li>
                <li>- Safari (Desktop)</li>
                <li>- Safari (Mobile)</li>
                <li>- Android Browser</li>
                <li>- Opera</li>
                <li>- Opera Mobile</li>
            </ul>
            
        
        
            <h4>Blocking and disabling cookies and similar technologies</h4>
        
            <p>Wherever you&apos;re located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser&apos;s help menu for more information.</p>
        
            <h4>Changes To Our Cookie Policy</h4>
        
            <p>We may change our Service and policies, and we may need to make changes to this Cookie Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Cookie Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Cookie Policy. If you do not want to agree to this or any updated Cookie Policy, you can delete your account.</p>
        
            <h4>Your Consent</h4>
        
            <p>By using our website, registering an account, or making a purchase, you hereby consent to our Cookie Policy and agree to its terms.</p>
        
            <h4>Errors and Omissions Disclaimer</h4>
        
            <p>TuringX is not responsible for any content, code or any other imprecision.</p>
            <p>TuringX does not provide warranties or guarantees.</p>
            <p>In no event shall the Company be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. TuringX Assist reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.</p>
        
            <h4>General Disclaimer</h4>
        
            <p>The TuringX Applications and Services and its contents are provided &quot;as is&quot; and &quot;as available&quot; without any warranty or representations of any kind, whether express or implied. TuringX is a distributor and not a publisher of the content supplied by third parties; as such, the Company exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via the Service. Without limiting the foregoing, the Company specifically disclaims all warranties and representations in any content transmitted on or in connection with the Services or on sites that may appear as links on the Services, or in the products provided as a part of, or otherwise in connection with, the Services, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by TuringX or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, the Company does not warrant that the Services will be uninterrupted, uncorrupted, timely, or error-free.</p>
        
            <h4>Contact Us</h4>
        
            <p>Don&apos;t hesitate to contact us if you have any questions regarding our Cookie Policy via email at <a href="mailto:support@assist.turingx.in">support@assist.turingx.in</a></p>
        
            <div className='subtext'>Last Updated: 1 January, 2024</div>
        
        
        </div>
          
    
  )
}
